- name: Installing FileBeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.17.0-x86_64.rpm
    state: present

- name: Copying File Beat template
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Restarting File Beat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes