COMPONENT: frontend
ARTIFACT_PATH: /usr/share/nginx/html
CATALOGUE_HOST: catalogue.kesavakadiyala.tech
USER_HOST: user.kesavakadiyala.tech
CART_HOST: cart.kesavakadiyala.tech
SHIPPING_HOST: shipping.kesavakadiyala.tech
PAYMENT_HOST: payment.kesavakadiyala.tech
