- name: Create MongoDB repo
  yum_repository:
    name: mongodb-org-4.2
    description: MongoDB Repository
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/4.2/x86_64/
    gpgcheck: yes
    enabled: yes
    gpgkey: https://www.mongodb.org/static/pgp/server-4.2.asc

- name: Installing Mongodb
  yum:
    name: mongodb-org
    state: latest

- name: Replacing Listen Address for Mongo
  replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Starting MongoDB
  systemd:
    name: mongod
    state: started
    enabled: yes

- name: Including AZ CLI Installation Steps
  include_role:
    name: common
    tasks_from: az-cli-setup

- name: Including Artifact Download Steps
  include_role:
    name: common
    tasks_from: artifact-download
  vars:
    component_id: 9720ff2d-f71d-437a-9f66-a8a9face2832

- name: Load MongoDB Schema
  shell: mongo < {{ item }}
  args:
    chdir: "{{ARTIFACT_PATH}}"
  loop:
    - catalogue.js
    - users.js