- name: Including Steps for Maven
  include_role:
    name: common
    tasks_from: maven
  vars:
    component_id: 45e7f3a0-c4d1-4cd3-8b31-4581f65ec775

- name: Including rsyslog role
  include_role:
    name: common
    tasks_from: rsyslog

- name: Setup Shipping Service
  template:
    src: shipping.service
    dest: /etc/systemd/system/shipping.service

- name: Start Shipping Service
  systemd:
    name: shipping
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include File Beat Role
  include_role:
    name: filebeat