- name: Variables Play
  hosts: web
  vars:
    URL: play-level-variable.com #Declaring play level variable
  tasks:
    - name: Accessing play Variable
      debug:
        msg: URL = {{URL}} #Accessing Variable
    - name: Declaring and Accessing task level variable
      vars:
        URL: task-level-variable.com
      debug:
        msg: URL = {{URL}}

- name: Declaring variables in file and accessing them
  hosts: web
  vars_files:
    - vars.yml # File where variable is declared
  tasks:
    - name: Accessing file level Variable
      debug:
        msg: URL = {{URL}}

- name: Declaring variables in inventory file and accessing variable
  hosts: web
  tasks:
    - name: Accessing variable from inventory file
      debug:
        msg: URL = {{URL}}

#Priority of Variables
#Lower the number Higher the priority.
#1. Task level Variable
#2. Play level Variable
