- name: Variables Play
  hosts: web
  vars:
    URL: play-level-variable.com #Declaring play level variable
  tasks:
    - name: Accessing play Variable
      debug:
        msg: URL = {{URL}} #Accessing Variable
    - name: Declaring and Accessing task level variable
      vars:
        URL: task-level-variable.com # Task level variable
      debug:
        msg: URL = {{URL}}

- name: Declaring variables in file and accessing them
  hosts: web
  vars_files:
    - vars.yml # File where variable is declared
  tasks:
    - name: Accessing file level Variable
      debug:
        msg: URL = {{URL}}

- name: Declaring variables in inventory file and accessing variable
  hosts: web
  tasks:
    - name: Accessing variable from inventory file
      debug:
        msg: URL = {{URL}}

- name: Accessing variables through prompt
  hosts: web
  vars_prompt:
    - name: URL
      prompt: Enter URL  # Script stops for providing variable value
      private: no
  tasks:
    - name: Accessing Prompt Variable
      debug:
        msg: URL = {{URL}}

#Priority of Variables
#Lower the number Higher the priority.
#0. Command line arguments given as -e VAR=DATA
#1. Task level Variable
#### Roles variables take precedence when you use roles.
#2. Play level Variable
# 3. vars_prompt
# 4. vars
# 5. Inventory

- name: Registering Variables
  hosts: all
  tasks:
    - name: Find files
      find:
        paths: /boot
      register: OUTPUT

    - name: Accessing registered variable
      debug:
        msg: OUTPUT = {{OUTPUT}}