#Ansible allows you to ‘become’ another user, different from the user that logged into the machine (remote user).
- name: Become
  hosts: localhost
  tasks:
    debug:
      msg: Become root user
    become: true

- name: Become
  hosts: localhost
  tasks:
    debug:
      msg: Become centos user
    become: true
    become_user: centos