- name: Become
  hosts: localhost
  tasks:
    - name: Become root user
      debug:
        msg: Become root user
      become: true

- name: Become
  hosts: localhost
  tasks:
    - name: Become centos user
      debug:
        msg: Become centos user
      become: true
      become_user: centos