- name: Become
  hosts: localhost
  tasks:
    - name: Become root user
      command: whoami
      become: true
      register: who
    - name: Printing register variable
      debug:
        msg: user = {{who.stdout_lines}}

- name: Become
  hosts: localhost
  tasks:
    - name: Become centos user
      command: whoami
      become: true
      become_user: centos
      register: who
    - name: Printing register variable
        debug:
          msg: user = {{who.stdout_lines}}