- name: Become
  hosts: localhost
  tasks:
    - name: Become root user
      command: who
      become: true

- name: Become
  hosts: localhost
  tasks:
    - name: Become centos user
      command: who
      become: true
      become_user: centos