- name: Roboshop Project ansible
  hosts: all
  become: true
  tasks:
    - name: Prechecks
      import_role:
        name: common
        tasks_from: pre-checks
      tags:
        - frontend
        - catalogue
        - mongodb
        - redis
        - user
        - cart

    - name: frontend
      import_role:
        name: frontend
      when: component == "frontend"
      tags:
        - frontend

    - name: catalogue
      import_role:
        name: catalogue
      when: component == "catalogue"
      tags:
        - catalogue

    - name: mongodb
      import_role:
        name: mongodb
      when: component == "mongodb"
      tags:
        - mongodb

    - name: redis
      import_role:
        name: redis
      when: component == "redis"
      tags:
        - redis

    - name: user
      import_role:
        name: user
      when: component == "user"
      tags:
        - user

    - name: cart
      import_role:
        name: cart
      when: component == "cart"
      tags:
        - cart