- name: Roboshop Project ansible
  hosts: all
  become: true
  tasks:
    - name: Precehcks
      import_role:
        name: common
        tasks_from: pre-checks
      tags:
        - frontend

    - name: frontend
      import_role:
        name: frontend
      when: component == "frontend"
      tags:
        - frontend