- name: Including Nodejs Installation
  include_role:
    name: common
    tasks_from: nodejs-installation

- name: Configuring user service
  template:
    src: user.service
    dest: /etc/systemd/system/user.service

- name: Start User Service
  systemd:
    name: user
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include File Beat Role
  include_role:
    name: filebeat