- name: Including Nodejs Installation
  include_role:
    name: common
    tasks_from: nodejs-installation

- name: Updating catalogue configuration
  template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Starting Catalogue application
  systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include File Beat Role
  include_role:
    name: filebeat