- name: Including Nodejs Installation
  include_role:
    name: common
    tasks_from: nodejs-installation

- name: Including rsyslog role
  include_role:
    name: common
    tasks_from: rsyslog

- name: Including AZ cli Installation steps
  include_role:
    name: common
    tasks_from: az-cli-setup

- name: Including application user creation role
  include_role:
    name: common
    tasks_from: application-user

- name: Creating catalogue directory
  file:
    path: "{{ARTIFACT_PATH}}"
    state: directory

- name: Downloading artifacts from azure
  include_role:
    name: common
    tasks_from: artifact-download

- name: Changing permissions of project directory
  file:
    path: "{{ARTIFACT_PATH}}"
    owner: roboshop
    group: roboshop

- name: Updating catalogue configuration
  template:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Starting Catalogue application
  systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include File Beat Role
  include_role:
    name: filebeat