- name: Download Node_Exporter
  unarchive:
    src: "{{URL}}"
    dest: /opt
    remote_src: yes

- name: Copy systemd file
  template:
    src: node_exporter.service
    dest: /etc/systemd/system
  notify: Restart Node Exporter

- name: Start Node Exporter
  systemd:
    name: node_exporter
    daemon_reload: yes
    state: started
    enabled: yes
