- name: Installing nodeJs and dependencies
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: latest

- name: Including rsyslog role
  include_tasks: rsyslog.yml

- name: Including application {{ COMPONENT }} creation role
  include_tasks: application-user.yml

- name: Including AZ cli Installation steps
  include_tasks: az-cli-setup.yml

- name: Creating {{ COMPONENT }} directory
  file:
    path: "{{ARTIFACT_PATH}}"
    state: directory

- name: Downloading artifacts from azure
  include_tasks: artifact-download.yml

- name: Changing permissions of project directory
  file:
    path: "{{ARTIFACT_PATH}}"
    owner: roboshop
    group: roboshop
