- name: Including Nodejs Installation
  include_role:
    name: common
    tasks_from: nodejs-installation
  vars:
    component_id: 84ff9b8e-fa0e-4c94-a2c2-dee2485aed61

- name: Configuring cart service
  template:
    src: cart.service
    dest: /etc/systemd/system/cart.service

- name: Start Cart Service
  systemd:
    name: cart
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Include Prometheus Role
  include_role:
    name: prometheus

- name: Include File Beat Role
  include_role:
    name: filebeat
#  vars:
#    LOG_FILE = /var/log/